### ISSUE TITLE
Centering is incorrect on Nexus 10 in landscape 

### ISSUE THREAD

**Issue by MikeWallaceDev** [Ramotion/paper-onboarding-android#10]
The two text views are left aligned instead of centered in the screen.

**Comment by oleg-vasiliev** [comment]
Please provide a screenshot or video clip.

**Comment by GoSwiftlyIntoThisGoodNight** [comment]
I am having this same problem on my Nexus 6P. 
![screenshot_20170119-144148](https://cloud.githubusercontent.com/assets/24399013/22128477/a6f9d914-de55-11e6-981b-9353dd71cbbe.png)

**Comment by elfel** [comment]
I also get left alignment on Nexus 6P, if text isn't long enough to fill full width.

**Comment by dreimanis** [comment]
On LG G4 , when I go to 2nd page it aligns left.

**Comment by abeemukthees** [comment]
Same issue, if text is single line

**Comment by oleg-vasiliev** [comment]
fixed in version 1.1.1
