### ISSUE TITLE
Cannot resolve method 'add(int, com.ramotion.paperonboarding.PaperOnboardingFragment)'

### ISSUE THREAD

**Issue by dsemelianov** [Ramotion/paper-onboarding-android#14]
Error occurs on the .add()
I tried casting onBoardingFragment to a regular Fragment, but it wouldn't take.

PaperOnboardingFragment onBoardingFragment = PaperOnboardingFragment.newInstance(elements);
FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
fragmentTransaction.add(R.id.fragment_container, onBoardingFragment);
fragmentTransaction.commit();

Any ideas for a fix?

**Comment by oleg-vasiliev** [comment]
Any details? Stacktrace maybe?

**Comment by iHombre** [comment]
Im just add support lib to classpath PaperOnboarding for fix.

**Comment by vedantkarandikar** [comment]
**SOLVED**

Use: 
`FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
        fragmentTransaction.add(R.id.run_chooser_container, onBoardingFragment);
        fragmentTransaction.commit();`

In the Gradle module for your app exclude `support` library for PaperOnBoarding like this, 
    compile `('com.ramotion.paperonboarding:paper-onboarding:1.1.1'){
    exclude group: 'com.android.support:appcompat-vXXXX'
    }`

or use 

`compile ('com.ramotion.paperonboarding:paper-onboarding:1.1.1'){ exclude group: 'com.android.support}`

But removing the entire support library is not recommended

**Comment by sarbogast** [comment]
I still have exactly the same issue and yet I excluded the appcompat dependency as such:

```
implementation('com.ramotion.paperonboarding:paper-onboarding:1.1.1'){
    exclude group: 'com.android.support:appcompat-v7'
}
```

And this following piece of code (in Kotlin) gives me an error on the third line:

```
val onboardingFragment = PaperOnboardingFragment.newInstance(arrayListOf(page1))
val onboardingTx = fragmentManager.beginTransaction()
onboardingTx.add(R.id.fragment_container, onboardingFragment)
onboardingTx.commit()
```

Because onboardingFragment is not a Fragment according to it.

**Comment by sarbogast** [comment]
I figured it out: since PaperOnboardingFragment is not an android.app.Fragment, but an android.support.v4.app, it should not be added to fragmentManager but to supportFragmentManager instead. And that works.

**Comment by enigmaIam** [comment]
I am still fight with this

**Comment by enigmaIam** [comment]
I am still fighting with this

**Comment by samilafta** [comment]
I want to use fragments instead of the normal text. I am having a problem implementing that. Any help?

**Comment by golovin47** [comment]
Hello, @samilafta. This repository contains paper-onboarding-fragment-example module, which you can run in Android Studio as an app and check how it's implemented inside.
