### ISSUE TITLE
Change text color, typeface, size

### ISSUE THREAD

**Issue by royherma** [Ramotion/paper-onboarding-android#15]
How can on customize these in each / all pages?

Thanks!

**Comment by rockerhieu** [comment]
When creating the TextView it uses applicationContext which discards all theming settings of the activity. Should have used the given context instead.

**Comment by royherma** [comment]
So @rockerhieu, it can't be changed?

**Comment by CeccoCQ** [comment]
+1

**Comment by StreethawkNick** [comment]
@royherma  @royherma  @CeccoCQ  This change if approved will allow you to customize text-color, typeface. 

https://github.com/Ramotion/paper-onboarding-android/pull/17

**Comment by rockerhieu** [comment]
@royherma can be, what I did was cloning the project and use activity context instead of application context.
