### ISSUE TITLE
Multiple images aren't loading

### ISSUE THREAD

**Issue by TrentPierce** [Ramotion/paper-onboarding-android#16]
I have three pages setup just as the readme says. When the fragment shows, the first image and icon show up. When I scroll to the second page, the icon shows, but no background image. Same with the third page. If I scroll back, none of the background images reappear.

**Comment by golovin47** [comment]
Hello, @TrentPierce. The best way to check various approaches of using this lib is to see inside paper-onboarding-fragment-example and paper-onboarding-simple-example modules. You can also ran any of them as an app in Android Studio.
