### ISSUE TITLE
App Stopped working

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [Ramotion/paper-onboarding-android#18]
When i call fragmenttransaction.commit() is gives me fatal exception main error so can anyone help me out with this ,,,,??

**Comment by golovin47** [comment]
Hello, @HasnainKhanNiazi. We couldn't reproduce this issue. The best way for you to check various approaches of using this lib is to look inside paper-onboarding-fragment-example and paper-onboarding-simple-example modules. Everything works perfectly there.
