### ISSUE TITLE
Reduce SDK requirement to at least 15

### ISSUE THREAD

**Issue by kibotu** [Ramotion/paper-onboarding-android#2]

**Comment by pmbfish40** [comment]
Hi @kibotu did you change it for sdk 15  ?

**Comment by kibotu** [comment]
yes

**Comment by kibotu** [comment]
well it won't show the circle reveal below lolipop though, since https://developer.android.com/reference/android/view/ViewAnimationUtils.html#createCircularReveal(android.view.View, int, int, float, float) requires >= 21, however it won't crash and the rest works just fine

**Comment by pmbfish40** [comment]
you can share it with me? is there github link?

**Comment by kibotu** [comment]
https://jitpack.io/#kibotu/paper-onboarding-android

**Comment by royorange** [comment]
com.github.ozodrukh:CircularReveal:1.3.1@aar is also a good idea I think.It can support at least sdk  
14+. You can check the sdk version and modified the "createBGAnimatorSet" method in PaperOnboardingEngine.java. Tested in 4.4 and worked well, hope that can help :)

**Comment by oleg-vasiliev** [comment]
will be reduced in version 1.1.
