### ISSUE TITLE
Setting images dynamically from url source

### ISSUE THREAD

**Issue by joreilly** [Ramotion/paper-onboarding-android#23]
I need to set `contentIconRes` and `bottomBarIconRes` images dynamically (from image loaded from url using say Picasso).  Is subclassing `PaperOnboardingEngine` the recommended way of doing that or is there another approach recommended?

**Comment by golovin47** [comment]
Hello, @joreilly. Right now there is no such feature in this lib. So, yes, if you need such behavior, you may customize PaperOnboardingEngine class.
