### ISSUE TITLE
change text color

### ISSUE THREAD

**Issue by pourya0111** [Ramotion/paper-onboarding-android#26]
how to change text color?

**Comment by pourya0111** [comment]
bump!! @Juriv

**Comment by zulkarnain-shah** [comment]
Really need this flexibility to change the color of both the title and description labels

**Comment by krazykira** [comment]
Once the PR #27  gets merged all you need to do is set a theme to the activity that uses `PaperOnboardingFragment`.

**manifest.xml**
```
  <activity
            android:name=".OnBoardingActivity"
            android:theme="@style/activityTheme"/>
```
**In styles.xml**

```
    <!--You can use any theme here as parent theme -->
    <style name="activityTheme" parent="AppTheme">
        <item name="android:textViewStyle">@style/myTextViewStyle</item>
    </style>

    <style name="myTextViewStyle" parent="@android:style/TextAppearance">
        <item name="android:textColor">#FFFFFF</item>
    </style>
```

**Comment by jonbulica99** [comment]
bump

**Comment by Vijaykumarj** [comment]
release version eagerly waiting for this feature

**Comment by CazimirRoman** [comment]
I have extended the PaperOnboardingEngine and overiden the method createContentTextView where is got a reference to the textviews: ((TextView) group.getChildAt(0)).setTextColor(Color.WHITE) and         ((TextView) group.getChildAt(1)).setTextColor(Color.WHITE); 
In the activity of fragment just create an instance of the extended class like this : 

CustomPaperOnboardingEngine engine = new CustomPaperOnboardingEngine(...)

Hope it helps!

**Comment by BillBunting** [comment]
Would also like an easier way to set the font and font color (need white) (like the iOS version)

**Comment by golovin47** [comment]
Hello. Right now there is no feature of changing text color inside lib. It uses your Application theme, so you may change text color in your app theme.

**Comment by SinanYilmaz9** [comment]
class MyPaperOnboardingEngine(
    var rootLayout: View,
    var contentElements: ArrayList<PaperOnboardingPage>, var appContext: Context
) : PaperOnboardingEngine(rootLayout, contentElements, appContext) {

    override fun createContentTextView(paperOnboardingPage: PaperOnboardingPage?): ViewGroup {
        val group = super.createContentTextView(paperOnboardingPage)
        (group.getChildAt(0) as TextView).setTextColor(Color.WHITE)
        (group.getChildAt(1) as TextView).setTextColor(Color.WHITE)
        return group
    }
    
}
That's great!

**Comment by Asendo316** [comment]
> CustomPaperOnboardingEngine

Can you please show us how you achieved this?

**Comment by nirajniroula** [comment]
For anyone still struggling with this issue, as suggested by @CazimirRoman, I first created a new class named `CustomPaperOnBoardEngine` and overrode its `createContentTextView` and change the text color of the TextView in there. Something like this:

```
public class CustomPaperOnBoardEngine extends PaperOnboardingEngine {
    public CustomPaperOnBoardEngine(View rootLayout, ArrayList<PaperOnboardingPage> contentElements, Context appContext) {
        super(rootLayout, contentElements, appContext);
    }

    @Override
    protected ViewGroup createContentTextView(PaperOnboardingPage PaperOnboardingPage) {

        ViewGroup group = super.createContentTextView(PaperOnboardingPage);
        ((TextView) group.getChildAt(0)).setTextColor(Color.WHITE);
        ((TextView) group.getChildAt(1)).setTextColor(Color.WHITE);
        return group;
    }
}
```

And in my activity where the `PaperOnboardingEngine` was used, I used `CustomPaperOnBoardEngine` instead. It works!
