### ISSUE TITLE
click listner not happen at onboarding_text layout  child ..ex textview 

### ISSUE THREAD

**Issue by abhishek8506** [Ramotion/paper-onboarding-android#31]
help me .. i want to add click listner on frame layout child , such as for skip .

**Comment by golovin47** [comment]
Hello, @abhishek8506. You can achieve it by creating your own fragment class which would extend PaperOnboardingFragment. In your custom fragment in method onCreateView() you should get the view by calling super.onCreateView(). Then you may add your view (for example TextView for skip) to view which you got from calling super.onCreateView().
