### ISSUE TITLE
Manifest allowBackup issue 

### ISSUE THREAD

**Issue by GorkemKarayel** [Ramotion/paper-onboarding-android#32]
Hi , 
I'm using AS 3.2 RC 3 to try.After adding the library gradle that synced. But I got an error;

	Attribute application@allowBackup value=(false) from AndroidManifest.xml:10:9-36
	is also present at [com.ramotion.paperonboarding:paper-onboarding:1.1.1] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:5-40:19 to override.

**Comment by golovin47** [comment]
Hello, @GorkemKarayel. Add tools:replace="android:allowBackup" to your app's Manifest element.
