### ISSUE TITLE
Add Skip Button?

### ISSUE THREAD

**Issue by BillBunting** [Ramotion/paper-onboarding-android#35]
How can a skip button be added?

**Comment by golovin47** [comment]
Hello, @BillBunting. Look here #31.

**Comment by fukemy** [comment]
@golovin47  
after look #31, still dont know how to do, please help

**Comment by golovin47** [comment]
Hello, @fukemy.

1. Create your own Fragment and extend it from PaperOnboardingFragment.
2. In your fragment's override method onCreateView(). In it add something like this: 
```View parentView = super.onCreateView();
     TextView skipTextview = findViewById(your textview id in layout);
     skipTextView.setOnClickListener(your click listener);
     ((ViewGroup)parentView.add).addView(YOUR_SKIP_TEXTVIEW);```

**Comment by fukemy** [comment]
thanks bro

**Comment by manimaran96** [comment]
> Hello, @fukemy.
> 
>     1. Create your own Fragment and extend it from PaperOnboardingFragment.
> 
>     2. In your fragment override method onCreateView(). In it add something like this:
> 
> 
> ```
> View parentView = super.onCreateView();
> TextView skipTextview = findViewById(your textview id in layout);
> skipTextView.setOnClickListener(your click listener);
> ((ViewGroup)parentView).addView(YOUR_SKIP_TEXTVIEW);
> ```

How implement in activity?
