### ISSUE TITLE
ERROR: Failed to resolve: com.ramotion.paperonboarding:paper-onboarding:1.1.2

### ISSUE THREAD

**Issue by mevivek** [Ramotion/paper-onboarding-android#38]
I am trying to add the dependency with `implementation 'com.ramotion.paperonboarding:paper-onboarding:1.1.2'` but showing error : _ERROR: Failed to resolve: com.ramotion.paperonboarding:paper-onboarding:1.1.2_

But adding `paper-onboarding:1.1.1` was successful.

compileSdkVersion 28
minSdkVersion 23
targetSdkVersion 28

repositories {
    google()
    jcenter()
}

**Comment by golovin47** [comment]
Hello, @mevivek. For some reason jcenter didn't update the version of the lib to the latest. For now you can add mavenCentral() to your repositories to use 1.1.2.

**Comment by golovin47** [comment]
We've uploaded new version 1.1.3 to maven and jcenter. Soon it should be available.
