### ISSUE TITLE
How to resolve this error from my project?

### ISSUE THREAD

**Issue by dhvanit-vavdiya** [Ramotion/paper-onboarding-android#40]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:13:5-174:19 to override.

**Comment by golovin47** [comment]
Hello, @dhvanit-vavdiya.This lib migrated to androidx. If you want to use this lib there are three options:
1. Migrate your project to androidx, which is inevitable anyway at some point of time.
2. Use previous version of this lib, which doesn't use androidx. For example 1.1.1.
3. Do as log suggests.
