### ISSUE TITLE
Incompatible with non-androidX projects

### ISSUE THREAD

**Issue by raphael-anydo** [Ramotion/paper-onboarding-android#42]
Hi.
Created a new project from scratch with Android Studio, without checking `use androidx`, added the `implementation 'com.ramotion.paperonboarding:paper-onboarding:1.1.3'` dependency.

Result: does not compile.

What went wrong:
`> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).`

Note: adding `'tools:replace="android:appComponentFactory"'` to <application> element at AndroidManifest.xml does not help.

I thought androidx libs were backward compatible with support library versions?

**Comment by golovin47** [comment]
To use this lib you need to migrate to androidX.

**Comment by raphael-anydo** [comment]
> To use this lib you need to migrate to androidX.

thanks. although that's currently a non priority migration for the project I wanted to implemented it on.
thanks anyways.
