### ISSUE TITLE
Android textcolor and icon color

### ISSUE THREAD

**Issue by testimonialz** [Ramotion/paper-onboarding-android#43]
Is there anyway that there could be an option for changing the android icon color's and also the text color please, I couldn't help notice that the ios version of the library has these features but the android does not.

**Comment by golovin47** [comment]
Hi @testimonialz. There are no such features in this lib, but you may fork it and add any functionality you need.

**Comment by testimonialz** [comment]
Alright thank you!

Thank you for your time.
________________________________
