### ISSUE TITLE
NullPointerException error

### ISSUE THREAD

**Issue by subhra9326** [Ramotion/paper-onboarding-android#44]
Your code converted into Kotlin 
---------------------------------
 val engine = PaperOnboardingEngine(findViewById(R.id.onboardingRootView), getDataForOnboarding(), applicationContext)
        engine.setOnChangeListener { oldElementIndex, newElementIndex -> Toast.makeText(applicationContext, "Swiped from $oldElementIndex to $newElementIndex", Toast.LENGTH_SHORT).show() }
        engine.setOnRightOutListener {
            // Probably here will be your exit action
            Toast.makeText(applicationContext, "Swiped out right", Toast.LENGTH_SHORT).show()
        }

I get error on R.id.onboardingRootView part 

Errror is : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.ramotion.paperonboarding.PaperOnboardingEngine.<init>(PaperOnboardingEngine.java:83)
        at io.insyssky.mediassistplus.activity.OnBoardActivity.onCreate(OnBoardActivity.kt:20)

**Comment by golovin47** [comment]
Hi, @subhra9326. I couldn't reproduce that issue. Try to look closer to example app presented in this repo, it works fine, so i think there is a minor error in your code.
