### ISSUE TITLE
Use of specific implementation of List for onBoarding pages

### ISSUE THREAD

**Issue by SippingCode** [Ramotion/paper-onboarding-android#47]
When creating the onboarding engine, we are forced to use an ArrayList to hold ou onboarding pages. This might be a design issue as using a List as constructor parameter would be better than an ArrayList.

For my case, i wanted to take advantage of LinkedList to keep the order of screen. This order in mind would help to better manipulated the screens in bounds to implement further logic

**Comment by golovin47** [comment]
Hello, @SippingCode. If you want to change something in this lib you may fork it and modify it for your needs.
