### ISSUE TITLE
It's not pretty clear that screen react on my swipe gesture

### ISSUE THREAD

**Issue by appspell** [Ramotion/paper-onboarding-android#49]
In my point of view, it would be better if a user can see that something happening when he/she swiping the screen.

the easier way to do it is to change background-color during swapping

If you think it is a good feature I may create a pull-request

**Comment by golovin47** [comment]
Hello @appspell. We will stick with current implementation. But this is an opensource lib, so anyone can fork it and add any feature he/she needs.
