### ISSUE TITLE
 can it support  android4.0?

### ISSUE THREAD

**Issue by LeaderChange** [Ramotion/paper-onboarding-android#6]
I really like this effect It supports the android version 4.0,?

**Comment by royorange** [comment]
You can use  lib CircularReveal to support device that 2.3+

**Comment by oleg-vasiliev** [comment]
SDK requirements already reduced to 15. For support old devices via CircularReveal library you can clone repo and fix code by yourself, it's very simple.
By supporting very old versions, you slow down the process of moving users to the new software.
